version: '3'

services:
  # Frontend service (Next.js)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - mindmaps-network

  # Backend service (Express.js)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=8080
      - MONGO_URI=mongodb://mongo:27017/Mindmaps  # Local database URL
    depends_on:
      - mongo
    networks:
      - mindmaps-network

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=Mindmaps
    volumes:
      - mongo-data:/data/db
    networks:
      - mindmaps-network

volumes:
  mongo-data:

networks:
  mindmaps-network:
    driver: bridge
